Fixed indentation (was tab instead of spaces)
File "/flask-datatables/flask_datatables/__init__.py", line 273
    total_records = self.total_recs
                                  ^
TabError: inconsistent use of tabs and spaces in indentation